version: '3'
services:
  api:
    build:
      context: .
      dockerfile: .docker/api/Dockerfile
    image: costs-to-expect
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      ##- /.docker/api/php/vendor
    links:
      - mysql
    env_file: .env
    environment:
        DB_HOST: ${DB_CONNECTION}
        DB_DATABASE: ${DB_DATABASE}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
  mysql:
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
