version: '3'
services:
    costs.api.app:
        build:
            context: .
            dockerfile: .docker/api/Dockerfile
        image: costs.api.app
        container_name: costs.api.app
        ports:
            - 8080:80
        volumes:
            - .:/var/www/html
        env_file: .env
        environment:
            TZ: UTC
            DB_HOST: ${DB_HOST}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
    costs.api.mysql:
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        image: costs.api.mysql
        container_name: costs.api.mysql
        ports:
            - 3308:3306
        env_file: .env
        environment:
            TZ: UTC
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
networks:
    default:
        name: costs.network
        external: true
